### PR TITLE
add paragraphes

### PR DESCRIPTION
**Pull request by n1c01a5**
- Quels sont les outils de base pour développer une dApp ?
- Comment créer une blockhain privée avec des noeuds ?

### CODE REVIEW

**Comment by dannywillems** [comment]
I will review tonight @n1c01a5.

**Comment by dannywillems** [comment]
@n1c01a5 Can you also explain more in detail the command `geth` and the parameters you used in
```bash
geth --datadir ./noeud1 --networkid "100" init genesis.json
```
? For example, what is `--datadir` and `--networkid`?

**Comment by dannywillems** [comment]
@n1c01a5
```
add-apt-repository -y ppa:ethereum/ethereum
add-apt-repository -y ppa:ethereum/ethereum-dev
```
Why do we need to add these two PPA? I suppose the second is for dev packages and the first is the stable? Could you explain or give a link where it's described/explained?

**Comment by dannywillems** [comment]
Else, it's OK for me.

**Comment by n1c01a5** [comment]
@dannywillems "For commands with apt, maybe add sudo?" I think is not a good idea maybe the user is root.

**Comment by dannywillems** [comment]
@n1c01a5 I don't really know if there's a lot of people who are always as root.

```
Pour lier, les noeuds entre eux il faut utiliser *bootnodes* de `geth`.
```
Remove the first comma and add one before *eux*.

**Comment by dannywillems** [comment]
@n1c01a5
`l'indentifiant` --> `l'identifiant`

**Comment by n1c01a5** [comment]
> I don't really know if there's a lot of people who are always as root.
yes but it's possible. I think `sudo` is too much. I hope user know this command.
> Why do we need to add these two PPA
To use `geth`
> Could you explain or give a link where it's described/explained?
I think is not necessary. I think the command is explicit. We need no documentation to understand theses commands.

**Comment by dannywillems** [comment]
@n1c01a5 As you want. Could I merge? If not, add to the title `DON'T MERGE` so I know I can't merge and remove it when it's ok by pinning me to say it's OK.

**Comment by n1c01a5** [comment]
The pull-request is not perfect but I think now there is no error. More later we can describe more the commands and the process.

**Comment by dannywillems** [comment]
@n1c01a5 So it can be merged? You won't add other files?

**Comment by n1c01a5** [comment]
@dannywillems yes you can merge :+1:

**Pull request merged**
